# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: containerizer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import mesos_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='containerizer.proto',
  package='',
  serialized_pb=_b('\n\x13\x63ontainerizer.proto\x1a\x0bmesos.proto\"\xd4\x01\n\x06Launch\x12\"\n\x0c\x63ontainer_id\x18\x01 \x02(\x0b\x32\x0c.ContainerID\x12\x1c\n\ttask_info\x18\x02 \x01(\x0b\x32\t.TaskInfo\x12$\n\rexecutor_info\x18\x03 \x01(\x0b\x32\r.ExecutorInfo\x12\x11\n\tdirectory\x18\x04 \x01(\t\x12\x0c\n\x04user\x18\x05 \x01(\t\x12\x1a\n\x08slave_id\x18\x06 \x01(\x0b\x32\x08.SlaveID\x12\x11\n\tslave_pid\x18\x07 \x01(\t\x12\x12\n\ncheckpoint\x18\x08 \x01(\x08\"J\n\x06Update\x12\"\n\x0c\x63ontainer_id\x18\x01 \x02(\x0b\x32\x0c.ContainerID\x12\x1c\n\tresources\x18\x02 \x03(\x0b\x32\t.Resource\"*\n\x04Wait\x12\"\n\x0c\x63ontainer_id\x18\x01 \x02(\x0b\x32\x0c.ContainerID\"-\n\x07\x44\x65stroy\x12\"\n\x0c\x63ontainer_id\x18\x01 \x02(\x0b\x32\x0c.ContainerID\"+\n\x05Usage\x12\"\n\x0c\x63ontainer_id\x18\x01 \x02(\x0b\x32\x0c.ContainerID\">\n\x0bTermination\x12\x0e\n\x06killed\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x02(\t\x12\x0e\n\x06status\x18\x03 \x01(\x05\".\n\nContainers\x12 \n\ncontainers\x18\x01 \x03(\x0b\x32\x0c.ContainerIDB(\n\x1eorg.apache.mesos.containerizerB\x06Protos')
  ,
  dependencies=[mesos_pb2.DESCRIPTOR, ])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LAUNCH = _descriptor.Descriptor(
  name='Launch',
  full_name='Launch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_id', full_name='Launch.container_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_info', full_name='Launch.task_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='executor_info', full_name='Launch.executor_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='directory', full_name='Launch.directory', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user', full_name='Launch.user', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slave_id', full_name='Launch.slave_id', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slave_pid', full_name='Launch.slave_pid', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='checkpoint', full_name='Launch.checkpoint', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=249,
)


_UPDATE = _descriptor.Descriptor(
  name='Update',
  full_name='Update',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_id', full_name='Update.container_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resources', full_name='Update.resources', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=325,
)


_WAIT = _descriptor.Descriptor(
  name='Wait',
  full_name='Wait',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_id', full_name='Wait.container_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=369,
)


_DESTROY = _descriptor.Descriptor(
  name='Destroy',
  full_name='Destroy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_id', full_name='Destroy.container_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=416,
)


_USAGE = _descriptor.Descriptor(
  name='Usage',
  full_name='Usage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_id', full_name='Usage.container_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=461,
)


_TERMINATION = _descriptor.Descriptor(
  name='Termination',
  full_name='Termination',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='killed', full_name='Termination.killed', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='Termination.message', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='Termination.status', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=525,
)


_CONTAINERS = _descriptor.Descriptor(
  name='Containers',
  full_name='Containers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='containers', full_name='Containers.containers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=573,
)

_LAUNCH.fields_by_name['container_id'].message_type = mesos_pb2._CONTAINERID
_LAUNCH.fields_by_name['task_info'].message_type = mesos_pb2._TASKINFO
_LAUNCH.fields_by_name['executor_info'].message_type = mesos_pb2._EXECUTORINFO
_LAUNCH.fields_by_name['slave_id'].message_type = mesos_pb2._SLAVEID
_UPDATE.fields_by_name['container_id'].message_type = mesos_pb2._CONTAINERID
_UPDATE.fields_by_name['resources'].message_type = mesos_pb2._RESOURCE
_WAIT.fields_by_name['container_id'].message_type = mesos_pb2._CONTAINERID
_DESTROY.fields_by_name['container_id'].message_type = mesos_pb2._CONTAINERID
_USAGE.fields_by_name['container_id'].message_type = mesos_pb2._CONTAINERID
_CONTAINERS.fields_by_name['containers'].message_type = mesos_pb2._CONTAINERID
DESCRIPTOR.message_types_by_name['Launch'] = _LAUNCH
DESCRIPTOR.message_types_by_name['Update'] = _UPDATE
DESCRIPTOR.message_types_by_name['Wait'] = _WAIT
DESCRIPTOR.message_types_by_name['Destroy'] = _DESTROY
DESCRIPTOR.message_types_by_name['Usage'] = _USAGE
DESCRIPTOR.message_types_by_name['Termination'] = _TERMINATION
DESCRIPTOR.message_types_by_name['Containers'] = _CONTAINERS

Launch = _reflection.GeneratedProtocolMessageType('Launch', (_message.Message,), dict(
  DESCRIPTOR = _LAUNCH,
  __module__ = 'containerizer_pb2'
  # @@protoc_insertion_point(class_scope:Launch)
  ))
_sym_db.RegisterMessage(Launch)

Update = _reflection.GeneratedProtocolMessageType('Update', (_message.Message,), dict(
  DESCRIPTOR = _UPDATE,
  __module__ = 'containerizer_pb2'
  # @@protoc_insertion_point(class_scope:Update)
  ))
_sym_db.RegisterMessage(Update)

Wait = _reflection.GeneratedProtocolMessageType('Wait', (_message.Message,), dict(
  DESCRIPTOR = _WAIT,
  __module__ = 'containerizer_pb2'
  # @@protoc_insertion_point(class_scope:Wait)
  ))
_sym_db.RegisterMessage(Wait)

Destroy = _reflection.GeneratedProtocolMessageType('Destroy', (_message.Message,), dict(
  DESCRIPTOR = _DESTROY,
  __module__ = 'containerizer_pb2'
  # @@protoc_insertion_point(class_scope:Destroy)
  ))
_sym_db.RegisterMessage(Destroy)

Usage = _reflection.GeneratedProtocolMessageType('Usage', (_message.Message,), dict(
  DESCRIPTOR = _USAGE,
  __module__ = 'containerizer_pb2'
  # @@protoc_insertion_point(class_scope:Usage)
  ))
_sym_db.RegisterMessage(Usage)

Termination = _reflection.GeneratedProtocolMessageType('Termination', (_message.Message,), dict(
  DESCRIPTOR = _TERMINATION,
  __module__ = 'containerizer_pb2'
  # @@protoc_insertion_point(class_scope:Termination)
  ))
_sym_db.RegisterMessage(Termination)

Containers = _reflection.GeneratedProtocolMessageType('Containers', (_message.Message,), dict(
  DESCRIPTOR = _CONTAINERS,
  __module__ = 'containerizer_pb2'
  # @@protoc_insertion_point(class_scope:Containers)
  ))
_sym_db.RegisterMessage(Containers)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036org.apache.mesos.containerizerB\006Protos'))
# @@protoc_insertion_point(module_scope)
